### PR TITLE
Hotfix/INV-707/Broken tooltip

### PR DESCRIPTION
**Pull request by jsconan**
### Summary

- [extension-tao-itemqti v29.14.4.10](https://github.com/oat-sa/extension-tao-itemqti/releases/tag/v29.14.4.10) Fix a runtime error preventing from editing a tooltip in the item authoring.

image

- [extension-pcisample v3.6.5](https://github.com/oat-sa/extension-pcisample/releases/tag/v3.6.5) Restore the tooltip helper in the textReader PCI.

image

### Details

- [extension-tao-itemqti v29.14.4.10](https://github.com/oat-sa/extension-tao-itemqti/releases/tag/v29.14.4.10)  Backport of https://github.com/oat-sa/extension-tao-itemqti/pull/2302
- [extension-pcisample v3.6.5](https://github.com/oat-sa/extension-pcisample/releases/tag/v3.6.5) When migrating the PCI to the IMS standard, we made some surgery to remove or adapt incompatible code. However, it was a tad too aggressive, and [the helper responsible for preparing the tooltip was removed together with the one that brought MathJAX](https://github.com/oat-sa/extension-pcisample/pull/87/files#diff-82c38155dd7370921087076be131fa5e089961d18643a4bdb36253e7ad5d3470L186).

### How to test
- install TAO from tao-community v2022.11.18
- check out the branch
- install from composer
- update TAO
- open an item and try to add or edit a tooltip
- have an item with the textReader PCI and some tooltips (you can use the ones attached to the ticket)
- publish a delivery (or pick up an existing one if any)
- take the test and check the tooltip works

### CODE REVIEW

**Review by bugalot — APPROVED** [review]
The PR looks good to me

**Review by jeethufoc — APPROVED** [review]
LGTM

**Review by chinnu-focaloid — APPROVED** [review]
LGTM

**Review by uncleempty — APPROVED** [review]
LGTM

**Pull request merged**
