### PR TITLE
Release 2023 05 2

### PR DESCRIPTION
**Pull request by rgomeztao**
coming from [https://oat-sa.atlassian.net/browse/AUT-3093](https://oat-sa.atlassian.net/browse/AUT-3093)

changelog: fix long math expressions on associate interaction

### CODE REVIEW

**Review by andreluizmachado — APPROVED** [review]
LGTM

**Comment by rgomeztao** [comment]
I have removed the generis update, it seems that the previous release branch 2023-25-1 had commits after being merged to master. I cleaned them as i dont know if they could cause issues

**Review by gabrielfs7 — APPROVED** [review]
Good job! @rgomeztao :) 

- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Comment by rgomeztao** [comment]
thanks @gabrielfs7 and @andreluizmachado !!!

**Pull request merged**
